apiVersion: v1
kind: Pod
metadata:
  name: gp3-username
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
  volumes:
  - name: scratch
    emptyDir: {}
  containers:
  - name: mypod
    image: nvcr.io/nvidia/pytorch:23.07-py3
    resources:
      limits:
        memory: 16Gi
        cpu: 4
        nvidia.com/gpu: 1
      requests:
        memory: 16Gi
        cpu: 4
        nvidia.com/gpu: 1
    command: ["/bin/bash", "-c"]
    args:
    - >-
        cd /scratch;
        wget https://raw.githubusercontent.com/pytorch/examples/main/mnist/main.py;
        nvidia-smi;
        python3 main.py;
    volumeMounts:
            - name: scratch
              mountPath: /scratch
